@URL = http://localhost:3333

@SESSION = 6547bf74-65ae-45d8-ac72-cf110e66cb10

###

GET {{URL}}/
Content-Type: application/json

###

GET {{URL}}/healthz
Content-Type: application/json

###

GET {{URL}}/users
Content-Type: application/json

###

GET {{URL}}/users/991d6b7b-8bd6-4b59-9430-8d257f16676b
Content-Type: application/json

###

GET {{URL}}/users/summary 
Cookie: sessionId={{SESSION}}

###

curl "{{URL}}/users/summary" \
    -H "Cookie: sessionId={{SESSION}}" \
    -H "Content-Type: application/json" \
    -H "Connection: keep-alive" \
    --compressed

###

POST {{URL}}/users
Content-Type: application/json

{
    "name": "tarantini"
}