@URL = http://localhost:3333
@URL = https://ignite-nodejs-02-api-1xme.onrender.com

@SESSION = 6547bf74-65ae-45d8-ac72-cf110e66cb10
#@SESSION = 08fa1a98-df52-412a-9fd9-fef914ee99ef
#@SESSION = bba98d32-cbf4-4159-9226-5e9e525187d5
#@SESSION = 91364d39-0be2-4ccf-b188-33cc6fe7296f
#@SESSION = fecf6114-95d4-4ce4-9d61-26524278fd8a


###

GET {{URL}}/
Content-Type: application/json

###

GET {{URL}}/healthz
Content-Type: application/json


###
GET {{URL}}/transactions
Content-Type: application/json
Cookie: sessionId={{SESSION}}

###


GET {{URL}}/transactions/3bf50320-674b-49ea-bbbf-b9a48e86f5b8
Content-Type: application/json
Cookie: sessionId={{SESSION}}

###

GET {{URL}}/transactions/summary 
Cookie: sessionId={{SESSION}}

###


POST {{URL}}/transactions
Content-Type: application/json
Cookie: sessionId={{SESSION}}

{
    "title": "ola mundo",
    "amount": 5,
    "type": "credit"
}

###
###
###


curl -v --cookie "sessionId={{SESSION}}" \
    -H "Content-Type: application/json" \
    -H "Connection: keep-alive" \
    "{{URL}}/transactions" \
    --compressed

###

curl "{{URL}}/transactions/summary" \
    -H "Cookie: sessionId={{SESSION}}" \
    -H "Content-Type: application/json" \
    -H "Connection: keep-alive" \
    --compressed

###
