@URL = http://localhost:3333
#@URL = https://ignite-nodejs-02-api-1xme.onrender.com

###

@SESSION = 0032267f-2ed4-4bb6-9313-2b9dc4b53b24

GET {{URL}}/
Content-Type: application/json

###

GET {{URL}}/healthz
Content-Type: application/json

###

GET {{URL}}/transactions
Content-Type: application/json

###

GET {{URL}}/transactions/{{SESSION}}
Content-Type: application/json

###

GET {{URL}}/transactions/summary 
Cookie: sessionId={{SESSION}}

###

curl "{{URL}}/transactions/summary" \
    -H "Cookie: sessionId={{SESSION}}" \
    -H "Content-Type: application/json" \
    -H "Connection: keep-alive" \
    --compressed

###

POST {{URL}}/transactions
Content-Type: application/json

{
    "title": "ola mundo",
    "amount": 15,
    "type": "credit"
}