
###

GET http://localhost:3333/transactions
Content-Type: application/json

###

GET http://localhost:3333/transactions/77eca52e-81e4-4f1b-9ad6-4b88d5bd08da
Content-Type: application/json

###

GET http://localhost:3333/transactions/summary 
Cookie: sessionId=bba98d32-cbf4-4159-9226-5e9e525187d4

###

curl "http://localhost:3333/transactions/summary" \
    -H "Cookie: sessionId=bba98d32-cbf4-4159-9226-5e9e525187d4" \
    -H "Content-Type: application/json" \
    -H "Connection: keep-alive" \
    --compressed

###

POST http://localhost:3333/transactions
Content-Type: application/json

{
    "title": "ola mundo",
    "amount": 10,
    "type": "credit"
}