@URL = http://localhost:3333

###

GET {{URL}}/
Content-Type: application/json

###
# @name create_user
POST {{URL}}/users
Content-Type: application/json

{
    "username": "teste6",
    "email": "teste6@test.com",
    "password": "123456"
}

